INFO:__main__:Using Mastodon access token: ljnlPF...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mastodon.social:443
DEBUG:urllib3.connectionpool:https://mastodon.social:443 "GET /api/v1/instance/ HTTP/11" 200 2093
DEBUG:schedule:Deleting *all* jobs
DEBUG:schedule:Deleting all jobs tagged "80c96866-3929-447f-8f2f-27cd1161147b"
INFO:__main__:Scheduling toot: üåü Your website deserves the best! üåü With our Web Hosting Packages at GenesisHostingTechnologies.com, you‚Äôll get speed, security, and 24/7 support to keep your site running smoothly. üöÄ Start today and take your online presence to new heights! üíª #WebHosting #HostingMadeEasy #GenesisHostingTech for everyday at 12:30
DEBUG:schedule:Deleting all jobs tagged "a8767349-f5ff-47fb-90dd-3a8d9536b508"
INFO:__main__:Scheduling toot: üåê Need web hosting that‚Äôs built to last? At GenesisHostingTechnologies.com, we offer Web Hosting Packages tailored to your needs‚Äîwhether it‚Äôs for a personal blog or a full-scale e-commerce site. üåü Sign up today and get started with the best in the business! üöÄ #WebHosting #GenesisHostingTech #SecureHosting for everyday at 14:30
DEBUG:schedule:Deleting all jobs tagged "82009bee-aa41-44b3-b54a-54fef347f61f"
INFO:__main__:Scheduling toot: üé∂ Take your streaming to the next level with AzuraCast packages at Genesis Hosting! Designed for audio streaming pros, our AzuraCast servers come pre-configured for seamless, powerful broadcasts. From automated scheduling to listener analytics, we've got everything you need to grow your audience. Start streaming now at genesishosting.tech! #Azuracast #Streaming #GenesisHosting for everyday at 15:00
DEBUG:schedule:Deleting all jobs tagged "5b8411a7-bd73-47d2-a4f1-9a8d19134a74"
INFO:__main__:Scheduling toot: üéß Ready to elevate your radio streaming? Our AzuraCast packages at Genesis Hosting are optimized for smooth, reliable audio streaming 24/7! With built-in scheduling, listener stats, and easy playlist management, you‚Äôll be live in no time. Your broadcast, your way‚Äîstart with us today at genesishosting.tech! #Azuracast #RadioStreaming #GenesisHosting for everyday at 08:00
DEBUG:schedule:Deleting all jobs tagged "d0409cfb-0796-4fbb-9104-bfbc2188d819"
INFO:__main__:Scheduling toot: Looking for crystal-clear communication? üéß Get your free TeamTalk server today from genesishosting.tech! Build your own community space with unlimited possibilities. üöÄ #TeamTalk #FreeServers #GenesisHostingTechnologies for everyday at 09:00
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5011
 * Running on http://38.102.127.173:5011
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:172.111.36.113 - - [29/Oct/2024 17:37:59] "[31m[1mGET /add HTTP/1.1[0m" 405 -
INFO:werkzeug:24.168.40.249 - - [29/Oct/2024 17:38:01] "[32mPOST /add HTTP/1.1[0m" 302 -
INFO:werkzeug:24.168.40.249 - - [29/Oct/2024 17:38:02] "GET /login?next=/add HTTP/1.1" 200 -
INFO:werkzeug:24.168.40.249 - - [29/Oct/2024 17:38:09] "[32mPOST /login HTTP/1.1[0m" 302 -
/home/doc/toot2/app.py:78: LegacyAPIWarning: The Query.get() method is considered legacy as of the 1.x series of SQLAlchemy and becomes a legacy construct in 2.0. The method is now available as Session.get() (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  return User.query.get(user_id)
INFO:werkzeug:24.168.40.249 - - [29/Oct/2024 17:38:09] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on /add [POST]
Traceback (most recent call last):
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(512)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/doc/toot2/app.py", line 109, in add_toot
    db.session.commit()
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2017, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1302, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1277, in _prepare_impl
    self.session.flush()
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4341, in flush
    self._flush(objects)
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4476, in _flush
    with util.safe_reraise():
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4437, in _flush
    flush_context.execute()
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/doc/toot2/toot2/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(512)

[SQL: INSERT INTO toot (id, message, toot_time, day) VALUES (%(id)s, %(message)s, %(toot_time)s, %(day)s)]
[parameters: {'id': '75676850-64a3-491f-9c78-789017709782', 'message': "Welcome to Genesis Hosting, where ordinary hosting is left far behind. At genesishosting.tech, we offer high-performance hosting solutions crafted fo ... (266 characters truncated) ...  or a digital overlord, Genesis Hosting is your dark ally, built to empower, not restrain. Dare to rise above the standard‚Äîyour online empire awaits.", 'toot_time': '07:00', 'day': 'everyday'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
INFO:werkzeug:24.168.40.249 - - [29/Oct/2024 17:38:18] "[35m[1mPOST /add HTTP/1.1[0m" 500 -
